### ISSUE TITLE
inference with single round conversation

### ISSUE THREAD

**Issue by HenryYuxuanWang** [ssbuild/aigc_zoo#1]
https://github.com/ssbuild/aigc_zoo/blob/1d2294a957a8e43ca913f654a4dbeacc578b1909/src/model_zoo/chatglm2/chatglm_model.py#L51-L56

这边应该和chatglm_finetuning保持一致？如果实在单轮对话的情况，也会变成Round 1: 问：答：的形式，与训练时的样式不匹配

**Comment by HenryYuxuanWang** [comment]
但是我在chatglm2训练过程中，发现在初始阶段出现比较难收敛的情况，然后查阅了chatglm2源码，其中的 build_inputs的方法确实与您之前build_inputs方法一致。 所以我在思考，这边chatglm2在单轮及多轮的情况下，与chatglm1相比，都强行要求把prompt构造成【Round X: 问：答：】的形式，是否由于chatglm2在SFT的过程中，数据构造形式已经采用了【Round X: 问：答：】的模式。所以源码中把build_inputs修改成这样的形式，为的是与其训练数据对齐，所以如果后续个人想要再次微调，训练数据也必须构造成【Round X: 问：答：】的形式。不知道楼主觉得我的推测是否有道理？

**Comment by ssbuild** [comment]
yeah ,  chatglm2 在推理和训练都使用的【Round X: 问：答：】模式 ， 准备在训练数据和推理也改成一致吧。
