### ISSUE TITLE
建议deep_training 和 aigc_zoo 合并

### ISSUE THREAD

**Issue by shell-nlp** [ssbuild/aigc_zoo#6]
建议模仿 paddlenlp,    把deep_training 和 aigc_zoo 合并，这样也可以少管理一个库的版本

**Comment by ssbuild** [comment]
aigc_zoo 只指针大语言模型 ，而且偏下游任务定制封装，不太适合封装到里面，本来是各个大模型微调模型 ，为了方便管理才独立出来 ， 也方便开发训练，推理，方便开发人员修改。

**Comment by shell-nlp** [comment]
好的，学到了
